### ISSUE TITLE
Dataset sample

### ISSUE THREAD

**Issue by malteos** [IllDepence/unarXive#1]
Hi all,

thank you very much for making this dataset public! 

Could you please provide a small sample of the data (max. 100MB)? That would make it much easier to get started with the dataset.

Best,
malte

**Comment by IllDepence** [comment]
Hi Malte,

I added a [small sample](https://github.com/IllDepence/unarXive/blob/master/doc/unarXive_sample.tar.bz2) to the repo (`doc/unarXive_sample.tar.bz2`) and included README files to explain the contents. Hope this helps. In case something's unclear about the contents let me know.

Best
Tarek
