### ISSUE TITLE
Is there any efficient way to retrieve the OpenAlex label in the IMRaD set?

### ISSUE THREAD

**Issue by SVLwoof** [IllDepence/unarXive#18]
Hi there,
I'm interested in classifying the IMRaD dataset and using the OpenAlex ID for each of the entries, like the ones in citrec.
Is there any efficient way to retrieve the label for each of them?

Thanks 🙂

**Comment by IllDepence** [comment]
Hi, thanks for the question. :)

I’m not sure I understand what information your looking for.
Maybe it helps if I lay out my understanding of things and than you can comment on that.

**IDs of cited documents**  
In the citrec data, the OpenAlex IDs given are IDs for *cited documents*. More specifically, the cited document corresponding to the single marker specified in each sample ([see data set card](https://huggingface.co/datasets/saier/unarXive_citrec#data-instances)).
Example: Paper A contains the paragraph “We compare our model to B [1] and C [2]”, then the citrec data would contain two samples with the paragraph. One for marker “[1]” with the OpenAlex ID of paper B, and one for maker “[2]” with the OpenAlex ID of paper C.
In the IMRaD data, a sample does not have a specified citation maker (many paragraphs will contain no citation markers at all), so I there is no equivalent to the OpenAlex IDs in the citrec data. 

**IDs of “source documents”**
If you’re interested in where the paragraphs originate from, both citrec and IMRaD data come with a file `license_info.jsonl` (see [here](https://huggingface.co/datasets/saier/unarXive_citrec#who-are-the-source-language-producers) and [here](https://huggingface.co/datasets/saier/unarXive_imrad_clf#who-are-the-source-language-producers)), which show for each paragraph from which arXiv document it was extracted. These “source documents” are specified by their arXiv ID.
