### ISSUE TITLE
Replicate for recent data from Arxiv and Openalex

### ISSUE THREAD

**Issue by shubhamagarwal92** [IllDepence/unarXive#22]
Hi! 
Thanks for open-sourcing the code! 
I would like to replicate the data for a small dataset of recently published work.  
I have a list of recent arxiv ids. How do I align them with the OpenAlex ids? I would also like to extract the citation graph and align with the arxiv ids for getting parsed full content. 

Is there an easy way without downloading huge amount of data (6TB arxiv and 300GB OpenAlex) for papers published say in August 2023?

**Comment by IllDepence** [comment]
Hi,

* I would assume the [arXiv bulk access methods](https://info.arxiv.org/help/bulk_data_s3.html) also include the possibility to selectively download only parts of the data, as this is needed for incremental updates of a local source dump.
* For OpenAlex you could look into their API and see if you can selectively grab the `works` entries for only the arXiv papers that you have (@johankit any other things you could think of?)

If you have that data prepared the [unarXive pipeline](https://github.com/IllDepence/unarXive/tree/master/src#recreating-unarxive) should be able to process if just fine. For creating the whole 1991–2022 data set we also processed multiple chunks of the data in parallel.

Hope this helps. :)

**Comment by shubhamagarwal92** [comment]
Thanks for your answer! Closing this now.
