### ISSUE TITLE
Is the data open source?

### ISSUE THREAD

**Issue by fishiu** [IllDepence/unarXive#6]
Hi, it is a great work to create such a comprehensive and latex-based paper dataset! May I ask that whether this whole dataset is open source and where I can download it if it is? Or only the extraction code is open source?

Thanks!

**Comment by IllDepence** [comment]
Hi,

the data set can be downloaded here: https://zenodo.org/record/4313164
The MIT license in this repository concerns the source code in the repository itself.
Regarding copyright questions please refer to the arXiv website: https://arxiv.org/help/license

**Comment by fishiu** [comment]
> Hi,
> 
> the data set can be downloaded here: https://zenodo.org/record/4313164 The MIT license in this repository concerns the source code in the repository itself. Regarding copyright questions please refer to the arXiv website: https://arxiv.org/help/license

Thank you very much!
